// src/components/Navbar.jsx
import { useState, useEffect } from 'react'
import { Link, useNavigate, useLocation } from 'react-router-dom'
import './Navbar.css' // aquí pones tus estilos
import logo from '/src/assets/ITO.png';

function Navbar() {
  const [showMenu, setShowMenu] = useState(false)
  const [usuario, setUsuario] = useState(null)
  const [rol, setRol] = useState(null)

  const navigate = useNavigate()
  const location = useLocation()

  // Cargar usuario desde localStorage
  const cargarUsuario = () => {
    const raw = localStorage.getItem('usuario')
    if (raw) {
      try {
        setUsuario(JSON.parse(raw))
      } catch (e) {
        setUsuario(null)
        localStorage.removeItem('usuario')
      }
    } else {
      setUsuario(null)
    }
    setRol(localStorage.getItem('rol'))
  }

  useEffect(() => {
    cargarUsuario()
  }, [])

  // Cada vez que cambias de ruta, refresca datos
  useEffect(() => {
    cargarUsuario()
  }, [location.pathname])

  const toggleMenu = () => {
    setShowMenu(!showMenu)
  }

  const irPerfil = () => {
    setShowMenu(false)
    navigate('/perfil')
  }

  const logout = () => {
    localStorage.removeItem('usuario')
    localStorage.removeItem('rol')
    localStorage.removeItem('token')
    setUsuario(null)
    setRol(null)
    setShowMenu(false)
    navigate('/login')
  }

  return (
    <nav className="navbar">
      <div className="navbar-brand">
        <Link to="/" className="brand-link">
          Instituto Tecnológico de Orizaba
        </Link>
      </div>

      {/* Centered logo */}
      <div className="brand-center">
        <Link to="/" className="brand-link-center">
          <img src={logo} alt="ITO" className="navbar-logo" />
        </Link>
      </div>

      <div className="navbar-menu">
        {/* Menú central vacío */}
      </div>

      <div className="navbar-user">
        {/* Panel de control solo para admin */}
        {usuario && rol === 'admin' && (
          <Link to="/admin" className="btn-nav btn-admin">
            Panel de control
          </Link>
        )}

        {/* Dropdown de usuario */}
        {usuario ? (
          <div className="user-dropdown">
            <button onClick={toggleMenu} className="btn-user">
              👤 {usuario.nombre}
            </button>
            {showMenu && (
              <div className="dropdown-menu">
                <button onClick={irPerfil} className="dropdown-item">
                  Modificar Perfil
                </button>
                <button onClick={logout} className="dropdown-item">
                  Cerrar Sesión
                </button>
              </div>
            )}
          </div>
        ) : (
          <div className="auth-buttons">
            <Link to="/login" className="btn-primary">Iniciar sesión</Link>
            <Link to="/register" className="btn-secondary">Registrarse</Link>
          </div>
        )}
      </div>
    </nav>
  )
}

export default Navbar

// src/app/components/navbar/navbar.component.ts
import { Component, ElementRef, HostListener, ViewChild } from '@angular/core';
import { Router, NavigationEnd } from '@angular/router';
import { NotificationService, NotificationItem } from '../../services/notification.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {
  usuario: any = null;
  rol: string | null = null;
  showMenu = false;
  showNotifs = false;
  notifs: NotificationItem[] = [];
  @ViewChild('notifMenu') notifMenuRef?: ElementRef;
  @ViewChild('bellBtn') bellBtnRef?: ElementRef;

  constructor(private router: Router, private notifSvc: NotificationService) {
    this.loadUser();
    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.loadUser();
      }
    });
    this.notifSvc.items$.subscribe(items => this.notifs = items);
  }

  loadUser() {
    try {
      const raw = localStorage.getItem('usuario');
      this.usuario = raw ? JSON.parse(raw) : null;
    } catch (e) {
      this.usuario = null;
    }
    this.rol = localStorage.getItem('rol');
  }

  toggleMenu() { this.showMenu = !this.showMenu; }
  toggleNotifs() { this.showNotifs = !this.showNotifs; }
  crearNotifsDesdeNoticias() {
    this.notifSvc.backfill(2).subscribe({
      next: (res) => {
        this.notifSvc.fetch();
        this.showNotifs = true;
      },
      error: () => {
        console.error('No se pudo crear notificaciones');
      }
    });
  }
  irPerfil() { this.showMenu = false; this.router.navigate(['/perfil']); }
  logout() {
    localStorage.removeItem('usuario');
    localStorage.removeItem('rol');
    localStorage.removeItem('token');
    this.usuario = null;
    this.rol = null;
    this.showMenu = false;
    this.router.navigate(['/login']);
  }

  @HostListener('document:keydown.escape')
  onEscKey() {
    this.showNotifs = false;
    this.showMenu = false;
  }

  @HostListener('document:click', ['$event'])
  onDocClick(ev: MouseEvent) {
    const target = ev.target as HTMLElement;
    const notifMenuEl = this.notifMenuRef?.nativeElement as HTMLElement | undefined;
    const bellBtnEl = this.bellBtnRef?.nativeElement as HTMLElement | undefined;
    if (this.showNotifs) {
      const insideMenu = notifMenuEl && notifMenuEl.contains(target);
      const onBell = bellBtnEl && bellBtnEl.contains(target);
      if (!insideMenu && !onBell) this.showNotifs = false;
    }
    if (this.showMenu) {
      const menuOpen = false; 
      if (!menuOpen && !target.closest('.btn-user') && !target.closest('.dropdown-menu')) {
        this.showMenu = false;
      }
    }
  }
}

<nav class="navbar">
  <div class="navbar-brand">
    <a routerLink="/" class="brand-link">Instituto Tecnológico de Orizaba</a>
  </div>

  <div class="brand-center">
    <a routerLink="/" class="brand-link-center">
      <img src="/assets/ITO.png" alt="ITO" class="navbar-logo" />
    </a>
  </div>

  <div class="navbar-menu"></div>

  <div class="navbar-user" style="position:relative;">
    <button #bellBtn *ngIf="usuario" (click)="toggleNotifs()" class="btn-nav btn-bell" title="Notificaciones">
      🔔 <span *ngIf="notifs.length" class="badge">{{notifs.length}}</span>
    </button>
    <div #notifMenu *ngIf="showNotifs" class="dropdown-menu notifs">
      <div *ngIf="rol==='admin'" class="notif-actions">
        <button class="btn-primary" (click)="crearNotifsDesdeNoticias()">Agregar notificaciones recientes</button>
      </div>
      <div *ngIf="!notifs.length" class="notif-empty">Sin notificaciones</div>
      <ul *ngIf="notifs.length" class="notif-list">
        <li *ngFor="let n of notifs" class="notif-item">
          <div class="title">{{n.titulo}}</div>
          <div class="msg">{{n.mensaje}}</div>
          <div class="meta">{{n.categoria}} • {{n.ts | date:'short'}}</div>
        </li>
      </ul>
    </div>
    <a *ngIf="usuario && rol === 'admin'" routerLink="/admin" class="btn-nav btn-admin">Panel de control</a>

    <div *ngIf="usuario; else anon">
      <button (click)="toggleMenu()" class="btn-user">👤 {{usuario.nombre}}</button>
      <div *ngIf="showMenu" class="dropdown-menu">
        <button (click)="irPerfil()" class="dropdown-item">Modificar Perfil</button>
        <button (click)="logout()" class="dropdown-item">Cerrar Sesión</button>
      </div>
    </div>

    <ng-template #anon>
      <div class="auth-buttons">
        <a routerLink="/login" class="btn-primary">Iniciar sesión</a>
        <a routerLink="/register" class="btn-secondary">Registrarse</a>
      </div>
    </ng-template>
  </div>
</nav>
