// src/views/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from '/src/context/AuthContext.jsx';
import { toast } from 'react-toastify';
import "./Login.css";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const navigate = useNavigate();
  const { login } = useAuth();

  const handleLogin = async (e) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      const res = await fetch("http://localhost:3000/auth/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email, password }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Error en la autenticación");
        setLoading(false);
        return;
      }

      if (data.usuario) {
        login(data.usuario, data.token);
      }

      setLoading(false);
      toast.success(data.message || 'Login exitoso');

      const rol = data.usuario?.rol;
      if (rol === "admin") {
        navigate("/admin");
      } else {
        navigate("/");
      }
    } catch (err) {
      console.error(err);
      setError("Error al conectarse al servidor");
      toast.error("Error al conectarse al servidor");
      setLoading(false);
    }
  };

  return (
    <div className="login-container">
      <div className="login-card">
        <h2>Iniciar Sesión</h2>

        <form onSubmit={handleLogin}>
          <div className="form-group">
            <label>Correo</label>
            <input
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label>Contraseña</label>
            <input
              type="password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>

          {error && <div className="form-error">{error}</div>}

          <button type="submit" className="btn-submit" disabled={loading}>
            {loading ? "Entrando..." : "Entrar"}
          </button>
        </form>
      </div>
    </div>
  );
}

// src/app/views/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { ToastrService } from 'ngx-toastr';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  email = '';
  password = '';
  loading = false;
  error: string | null = null;

  constructor(private http: HttpClient, private router: Router, private toastr: ToastrService) {}

  async handleLogin() {
    if (!this.email || !this.password) {
      this.toastr.error('Por favor completa todos los campos');
      return;
    }
    this.error = null;
    this.loading = true;
    try {
      const res: any = await firstValueFrom(
        this.http.post(`${environment.apiBase}/auth/login`, { email: this.email, password: this.password })
      );
      if (res.usuario) {
        localStorage.setItem('usuario', JSON.stringify(res.usuario));
        localStorage.setItem('token', res.token || '');
        localStorage.setItem('rol', res.usuario.rol || '');
      }
      this.toastr.success('Login exitoso');
      const rol = res.usuario?.rol;
      if (rol === 'admin') this.router.navigate(['/admin']); else this.router.navigate(['/']);
    } catch (err: any) {
      const errMsg = err?.error?.error || err?.error?.message || 'Error al autenticarse';
      this.error = errMsg;
      this.toastr.error(errMsg);
      console.error('Login error:', err);
    } finally { this.loading = false; }
  }
}


<div class="login-container">
  <div class="login-card">
    <h2>Iniciar Sesión</h2>
    <form (ngSubmit)="handleLogin()">
      <div class="form-group">
        <label>Correo</label>
        <input type="email" [(ngModel)]="email" name="email" required />
      </div>
      <div class="form-group">
        <label>Contraseña</label>
        <input type="password" [(ngModel)]="password" name="password" required />
      </div>
      <div *ngIf="error" class="form-error">{{error}}</div>
      <button class="btn-submit" type="submit" [disabled]="loading">{{loading? 'Entrando...':'Entrar'}}</button>
    </form>
  </div>
</div>
