// src/app/views/admin-panel/admin-panel.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { NoticiasService } from '../../services/noticias.service';
import { AuthService } from '../../services/auth.service';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-admin-panel',
  templateUrl: './admin-panel.component.html',
  styleUrls: ['./admin-panel.component.css']
})
export class AdminPanelComponent implements OnInit {
  usuario: any = null;
  noticias: any[] = [];
  loading = true;

  // crear
  titulo = '';
  contenido = '';
  imagen: File | null = null;
  archivo: File | null = null;
  creating = false;

  // editar
  editing = false;
  editId: any = null;
  editTitulo = '';
  editContenido = '';
  editImagen: File | null = null;
  editArchivo: File | null = null;

  constructor(
    private noticiasSvc: NoticiasService,
    private auth: AuthService,
    private router: Router,
    private toastr: ToastrService
  ) {}

  ngOnInit(): void {
    this.usuario = this.auth.getUser();
    if (!this.usuario || this.usuario.rol !== 'admin') {
      this.router.navigate(['/']);
      return;
    }
    this.loadNoticias();
  }

  async loadNoticias() {
    this.loading = true;
    try {
      this.noticias = await this.noticiasSvc.list();
    } catch (err) {
      console.error('Error cargando noticias', err);
      this.noticias = [];
    } finally {
      this.loading = false;
    }
  }

  onImagenChange(e: any) { this.imagen = e.target.files?.[0] || null; }
  onArchivoChange(e: any) { this.archivo = e.target.files?.[0] || null; }
  onEditImagenChange(e: any) { this.editImagen = e.target.files?.[0] || null; }
  onEditArchivoChange(e: any) { this.editArchivo = e.target.files?.[0] || null; }

  async crearNoticia() {
    if (!this.usuario || this.usuario.rol !== 'admin') return;
    if (!this.titulo || !this.contenido) { this.toastr.error('Título y contenido son obligatorios'); return; }
    if (this.imagen && this.imagen.size > 2 * 1024 * 1024) { this.toastr.error('Imagen demasiado grande (máx 2 MB)'); return; }
    if (this.archivo && this.archivo.size > 5 * 1024 * 1024) { this.toastr.error('Archivo demasiado grande (máx 5 MB)'); return; }
    this.creating = true;
    try {
      const fd = new FormData();
      fd.append('titulo', this.titulo);
      fd.append('contenido', this.contenido);
      fd.append('rol', this.usuario.rol);
      if (this.imagen) fd.append('imagen', this.imagen);
      if (this.archivo) fd.append('archivo', this.archivo);
      const res = await this.noticiasSvc.create(fd);
      this.titulo = '';
      this.contenido = '';
      this.imagen = null;
      this.archivo = null;
      this.toastr.success('✓ Noticia creada correctamente', 'Éxito', { positionClass: 'toast-top-right', timeOut: 3000 });
      await this.loadNoticias();
    } catch (err: any) {
      const errMsg = err?.error?.error || err?.message || 'Error al crear la noticia';
      this.toastr.error('✗ ' + errMsg, 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      console.error('Error crear noticia', err);
    } finally { this.creating = false; }
  }

  startEdit(n: any) {
    this.editing = true;
    this.editId = n.id;
    this.editTitulo = n.titulo;
    this.editContenido = n.contenido;
    this.editImagen = null;
    this.editArchivo = null;
  }

  cancelEdit() {
    this.editing = false;
    this.editId = null;
    this.editTitulo = '';
    this.editContenido = '';
  }

  async guardarEdicion() {
    if (!this.usuario || this.usuario.rol !== 'admin') return;
    try {
      const fd = new FormData();
      fd.append('titulo', this.editTitulo);
      fd.append('contenido', this.editContenido);
      fd.append('rol', this.usuario.rol);
      if (this.editImagen) fd.append('imagen', this.editImagen);
      if (this.editArchivo) fd.append('archivo', this.editArchivo);
      const res = await this.noticiasSvc.update(this.editId, fd);
      this.cancelEdit();
      this.toastr.success('✓ Noticia actualizada correctamente', 'Éxito', { positionClass: 'toast-top-right', timeOut: 3000 });
      await this.loadNoticias();
    } catch (err: any) {
      const errMsg = err?.error?.error || err?.message || 'Error al editar la noticia';
      this.toastr.error('✗ ' + errMsg, 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      console.error('Error editar noticia', err);
    }
  }

  async eliminar(id: any) {
    if (!this.usuario || this.usuario.rol !== 'admin') return;
    if (!confirm('¿Eliminar noticia?')) return;
    try {
      const res = await this.noticiasSvc.delete(id, { rol: this.usuario.rol } as any);
      this.toastr.success('✓ Noticia eliminada correctamente', 'Éxito', { positionClass: 'toast-top-right', timeOut: 3000 });
      await this.loadNoticias();
    } catch (err: any) {
      const errMsg = err?.error?.error || err?.message || 'Error al eliminar la noticia';
      this.toastr.error('✗ ' + errMsg, 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      console.error('Error eliminar', err);
    }
  }
}

<div class="admin-panel-container">
  <h1>Panel de administración</h1>

  <section class="create-section">
    <h2>Crear noticia</h2>
    <form (ngSubmit)="crearNoticia()">
      <div class="form-group">
        <label>Título</label>
        <input [(ngModel)]="titulo" name="titulo" type="text" required />
      </div>

      <div class="form-group">
        <label>Contenido</label>
        <textarea [(ngModel)]="contenido" name="contenido" rows="4" required></textarea>
      </div>

      <div class="form-row">
        <div class="form-group">
          <label>Imagen (opcional)</label>
          <input type="file" accept="image/*" (change)="onImagenChange($event)" />
          <small>JPG/PNG máximo 2 MB</small>
        </div>

        <div class="form-group">
          <label>Archivo adjunto (opcional)</label>
          <input type="file" (change)="onArchivoChange($event)" />
          <small>PDF/DOCX máximo 5 MB</small>
        </div>
      </div>

      <div class="form-actions">
        <button type="submit" [disabled]="creating">{{ creating ? 'Creando...' : 'Crear noticia' }}</button>
      </div>
    </form>
  </section>

  <section class="manage-section">
    <h2>Noticias existentes</h2>

    <div *ngIf="loading">Cargando noticias...</div>
    <div *ngIf="!loading && noticias.length === 0">No hay noticias registradas.</div>

    <div class="announcements-list" *ngIf="!loading && noticias.length > 0">
      <article *ngFor="let n of noticias" class="announcement-item">
        <div class="item-info">
          <h3>{{ n.titulo }}</h3>
          <p>{{ n.contenido }}</p>
          <div class="item-meta">
            <span>{{ n.fecha | date:'short' }}</span>
            <span *ngIf="n.imagen_url">Imagen: <a [href]="'http://localhost:3000' + n.imagen_url" target="_blank">Ver</a></span>
            <span *ngIf="n.archivo_url">Archivo: <a [href]="'http://localhost:3000' + n.archivo_url" target="_blank">Descargar</a></span>
          </div>
        </div>

        <div class="item-actions">
          <button (click)="startEdit(n)">Editar</button>
          <button (click)="eliminar(n.id)">Eliminar</button>
        </div>
      </article>
    </div>
  </section>

  <div class="edit-modal" *ngIf="editing">
    <div class="edit-card">
      <h3>Editar noticia</h3>
      <div class="form-group">
        <label>Título</label>
        <input [(ngModel)]="editTitulo" name="editTitulo" />
      </div>
      <div class="form-group">
        <label>Contenido</label>
        <textarea [(ngModel)]="editContenido" name="editContenido" rows="4"></textarea>
      </div>
      <div class="form-row">
        <div class="form-group">
          <label>Imagen nueva</label>
          <input type="file" accept="image/*" (change)="onEditImagenChange($event)" />
        </div>
        <div class="form-group">
          <label>Archivo nuevo</label>
          <input type="file" (change)="onEditArchivoChange($event)" />
        </div>
      </div>
      <div class="form-actions">
        <button (click)="guardarEdicion()">Guardar</button>
        <button (click)="cancelEdit()">Cancelar</button>
      </div>
    </div>
  </div>
</div>

// src/views/AdminPanel.jsx
import React, { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import "./AdminPanel.css";
import Modal from '/src/components/Modal.jsx';
import { toast } from 'react-toastify';

const apiBase = "http://localhost:3000";

export default function AdminPanel() {
  const navigate = useNavigate();

  const [titulo, setTitulo] = useState("");
  const [contenido, setContenido] = useState("");
  const imagenInputRef = useRef(null);
  const archivoInputRef = useRef(null);
  const [imagen, setImagen] = useState(null);
  const [archivo, setArchivo] = useState(null);

  const [noticias, setNoticias] = useState([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);

  const [editing, setEditing] = useState(false);
  const [editId, setEditId] = useState(null);
  const [editTitulo, setEditTitulo] = useState("");
  const [editContenido, setEditContenido] = useState("");
  const editImagenInputRef = useRef(null);
  const editArchivoInputRef = useRef(null);
  const [editImagen, setEditImagen] = useState(null);
  const [editArchivo, setEditArchivo] = useState(null);

  const [usuario, setUsuario] = useState(null);

  useEffect(() => {
    try {
      const raw = localStorage.getItem("usuario");
      setUsuario(raw ? JSON.parse(raw) : null);
    } catch (e) {
      setUsuario(null);
      localStorage.removeItem("usuario");
    }
  }, []);

  const esAdmin = usuario && usuario.rol === "admin";

  const onImagenChange = (e) => {
    setImagen(e.target.files[0] || null);
  };

  const onArchivoChange = (e) => {
    setArchivo(e.target.files[0] || null);
  };

  const onEditImagenChange = (e) => {
    setEditImagen(e.target.files[0] || null);
  };

  const onEditArchivoChange = (e) => {
    setEditArchivo(e.target.files[0] || null);
  };

  const fetchNoticias = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${apiBase}/noticias`);
      if (!res.ok) {
        const txt = await res.text();
        console.error("Error HTTP al cargar noticias:", res.status, txt);
        toast.error("Error al cargar noticias (HTTP " + res.status + ")");
        return;
      }
      const data = await res.json();
      setNoticias(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Error de red al cargar noticias:", err);
      toast.error("Error de red al cargar noticias");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNoticias();
  }, []);

  const crearNoticia = async (e) => {
    e?.preventDefault?.();
    if (!esAdmin) return toast.error("No autorizado") && null;
    if (imagen && imagen.size > 2 * 1024 * 1024) {
      return toast.error("La imagen excede el tamaño máximo recomendado de 2 MB.");
    }
    if (archivo && archivo.size > 5 * 1024 * 1024) {
      return toast.error("El archivo excede el tamaño máximo recomendado de 5 MB.");
    }

    setCreating(true);
    try {
      const formData = new FormData();
      formData.append("titulo", titulo);
      formData.append("contenido", contenido);
      formData.append("rol", usuario.rol);
      if (imagen) formData.append("imagen", imagen);
      if (archivo) formData.append("archivo", archivo);

      const res = await fetch(`${apiBase}/noticias`, {
        method: "POST",
        body: formData,
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        console.error("Respuesta no OK:", res.status, data);
        toast.error(data.error || `Error al crear noticia (HTTP ${res.status})`);
        setCreating(false);
        return;
      }

      toast.success(data.message || "Noticia creada");

      setTitulo("");
      setContenido("");
      setImagen(null);
      setArchivo(null);
      if (imagenInputRef.current) imagenInputRef.current.value = "";
      if (archivoInputRef.current) archivoInputRef.current.value = "";

      if (data.noticia) {
        setNoticias((prev) => [data.noticia, ...prev]);
      } else {
        await fetchNoticias();
      }
    } catch (err) {
      console.error(err);
      toast.error("Error al crear noticia");
    } finally {
      setCreating(false);
    }
  };

  const startEdit = (n) => {
    setEditing(true);
    setEditId(n.id);
    setEditTitulo(n.titulo);
    setEditContenido(n.contenido);
    setEditImagen(null);
    setEditArchivo(null);
    if (editImagenInputRef.current) editImagenInputRef.current.value = "";
    if (editArchivoInputRef.current) editArchivoInputRef.current.value = "";
  };

  const cancelEdit = () => {
    setEditing(false);
    setEditId(null);
    setEditTitulo("");
    setEditContenido("");
    setEditImagen(null);
    setEditArchivo(null);
    if (editImagenInputRef.current) editImagenInputRef.current.value = "";
    if (editArchivoInputRef.current) editArchivoInputRef.current.value = "";
  };

  const guardarEdicion = async () => {
    if (!esAdmin) return toast.error("No autorizado") && null;
    try {
      const formData = new FormData();
      formData.append("titulo", editTitulo);
      formData.append("contenido", editContenido);
      formData.append("rol", usuario.rol);
      if (editImagen) formData.append("imagen", editImagen);
      if (editArchivo) formData.append("archivo", editArchivo);

      const res = await fetch(`${apiBase}/noticias/${editId}`, {
        method: "PUT",
        body: formData,
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        console.error("Error editar:", res.status, data);
        toast.error(data.error || `Error al editar (HTTP ${res.status})`);
        return;
      }

      toast.success(data.message || "Editada");
      cancelEdit();
      await fetchNoticias();
    } catch (err) {
      console.error(err);
      toast.error("Error al editar noticia");
    }
  };

  const eliminar = async (id) => {
    if (!esAdmin) return toast.error("No autorizado") && null;
    if (!window.confirm("¿Eliminar noticia?")) return;
    try {
      const res = await fetch(`${apiBase}/noticias/${id}`, {
        method: "DELETE",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rol: usuario.rol }),
      });

      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        console.error("Error eliminar:", res.status, data);
        toast.error(data.error || `Error al eliminar (HTTP ${res.status})`);
        return;
      }

      toast.success(data.message || "Eliminada");
      await fetchNoticias();
    } catch (err) {
      console.error(err);
      toast.error("Error al eliminar noticia");
    }
  };

  const formatFecha = (f) => {
    try {
      return new Date(f).toLocaleString();
    } catch {
      return f;
    }
  };

  const editingNoticia = noticias.find((x) => x.id === editId) || null;

  useEffect(() => {
    if (usuario === null) {
    } else if (!esAdmin) {
    }
  }, [usuario]);

  return (
    <div className="admin-panel-container">
      <h1>Panel de administración</h1>

      <section className="create-section">
        <h2>Crear noticia</h2>

        <form className="announcement-form" onSubmit={crearNoticia}>
          <div className="form-group">
            <label>Título</label>
            <input
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
              type="text"
              placeholder="Título de la noticia"
              required
            />
          </div>

          <div className="form-group">
            <label>Contenido</label>
            <textarea
              value={contenido}
              onChange={(e) => setContenido(e.target.value)}
              rows="4"
              placeholder="Escribe el contenido de la noticia"
              required
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label>Imagen (opcional)</label>

              <label className="file-label">
                Seleccionar imagen
                <input
                  ref={imagenInputRef}
                  type="file"
                  className="file-input"
                  accept="image/*"
                  onChange={onImagenChange}
                />
              </label>

              <small>Formatos recomendados: JPG, PNG, máximo 2&nbsp;MB.</small>
            </div>

            <div className="form-group">
              <label>Archivo adjunto (opcional)</label>

              <label className="file-label">
                Seleccionar archivo
                <input
                  ref={archivoInputRef}
                  type="file"
                  className="file-input"
                  onChange={onArchivoChange}
                />
              </label>

              <small>PDF, DOCX, etc., máximo 5&nbsp;MB.</small>
            </div>
          </div>

          <div className="form-actions">
            <button type="submit" className="btn-submit" disabled={creating}>
              {creating ? "Creando..." : "Crear noticia"}
            </button>
          </div>
        </form>
      </section>

      {/* EDITOR DE noticia */}
      <Modal open={editing} onClose={cancelEdit}>
        <h2 style={{ textAlign: 'center', marginBottom: 12 }}>Editar noticia</h2>

        <div className="form-group">
          <label>Título</label>
          <input
            value={editTitulo}
            onChange={(e) => setEditTitulo(e.target.value)}
            type="text"
            required
          />
        </div>

        <div className="form-group">
          <label>Contenido</label>
          <textarea
            value={editContenido}
            onChange={(e) => setEditContenido(e.target.value)}
            rows="4"
            required
          />
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Imagen actual</label>
            {editingNoticia && editingNoticia.imagen_url ? (
              <div>
                <img src={apiBase + editingNoticia.imagen_url} alt="Imagen actual" className="news-image" />
              </div>
            ) : (
              <div>
                <small>No hay imagen adjunta.</small>
              </div>
            )}

            <label className="file-label">
              Seleccionar nueva imagen
              <input
                ref={editImagenInputRef}
                type="file"
                accept="image/*"
                className="file-input"
                onChange={onEditImagenChange}
              />
            </label>
            <small>Si no seleccionas nada, se mantiene la imagen actual.</small>
          </div>

          <div className="form-group">
            <label>Archivo actual</label>
            {editingNoticia && editingNoticia.archivo_url ? (
              <div>
                <a href={apiBase + editingNoticia.archivo_url} target="_blank" rel="noreferrer">Ver archivo</a>
              </div>
            ) : (
              <div>
                <small>No hay archivo adjunto.</small>
              </div>
            )}

            <label className="file-label">
              Seleccionar nuevo archivo
              <input
                ref={editArchivoInputRef}
                type="file"
                className="file-input"
                onChange={onEditArchivoChange}
              />
            </label>
            <small>Si no seleccionas nada, se mantiene el archivo actual.</small>
          </div>
        </div>

        <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 14 }}>
          <button className="btn-save" onClick={guardarEdicion}>Guardar cambios</button>
          <button className="btn-cancel" onClick={cancelEdit}>Cancelar</button>
        </div>
      </Modal>

      <section className="manage-section">
        <h2>Noticias existentes</h2>

        {loading ? (
          <div className="no-announcements">Cargando noticias...</div>
        ) : noticias.length === 0 ? (
          <div className="no-announcements">No hay noticias registradas.</div>
        ) : (
          <div className="announcements-list">
            {noticias.map((n) => (
              <article key={n.id} className="announcement-item">
                <div className="item-header">
                  <div className="item-info">
                    <h3>{n.titulo}</h3>
                    <p>{n.contenido}</p>

                    <div className="item-meta">
                      <span>{formatFecha(n.fecha)}</span>

                      {n.imagen_url && (
                        <span>
                          Imagen:{" "}
                          <a href={apiBase + n.imagen_url} target="_blank" rel="noreferrer">
                            Ver
                          </a>
                        </span>
                      )}

                      {n.archivo_url && (
                        <span>
                          Archivo:{" "}
                          <a href={apiBase + n.archivo_url} target="_blank" rel="noreferrer">
                            Descargar
                          </a>
                        </span>
                      )}
                    </div>
                  </div>

                  <div className="item-actions">
                    <button className="btn-edit" onClick={() => startEdit(n)}>
                      Editar
                    </button>
                    <button className="btn-delete" onClick={() => eliminar(n.id)}>
                      Eliminar
                    </button>
                  </div>
                </div>
              </article>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
