// src/app/views/home/home.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { ToastrService } from 'ngx-toastr';
import { toSignal } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  private _noticias = signal<any[]>([]);
  private _loading = signal(true);
  environment = environment;
  constructor(private http: HttpClient, private toastr: ToastrService) {}
  ngOnInit(): void {
    this.fetchNoticiasSignal();
  }
  fetchNoticiasSignal() {
    this._loading.set(true);
    try {
      this.http.get(`${environment.apiBase}/noticias`).subscribe({
        next: (res: any) => {
          this._noticias.set(Array.isArray(res) ? res : []);
        },
        error: (err) => {
          console.error(err);
          this.toastr.error('✗ Error al cargar noticias', 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
          this._noticias.set([]);
        },
        complete: () => {
          this._loading.set(false);
        }
      });
    } catch (err) {
      console.error(err);
      this.toastr.error('✗ Error al cargar noticias', 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      this._noticias.set([]);
      this._loading.set(false);
    }
  }
  formatFecha(f: any) { try { return new Date(f).toLocaleString(); } catch { return f; } }
  get noticias() { return this._noticias(); }
  get loading() { return this._loading(); }
  get isAdmin() { return (localStorage.getItem('rol') || '') === 'admin'; }
}

<div class="home-container">
  <section class="home-banner">
    <h1>Noticias</h1>
    <p>"Lo nuevo del Tec en un solo lugar: eventos, anuncios y lo más top. ¡No te pierdas nada!"</p>
    <a *ngIf="isAdmin" routerLink="/admin" class="btn-primary">Ir a agregar noticias</a>
  </section>

  <section class="announcements-section">
    <h2>Noticias recientes</h2>

    <div *ngIf="loading">Cargando noticias...</div>

    <div class="announcements-grid" *ngIf="!loading">
      <article *ngIf="noticias.length === 0" class="announcement-card empty-card">
        <div class="card-content">
          <h3>Sin noticias por ahora</h3>
          <p class="card-preview">Aún no se han publicado avisos. Vuelve más tarde.</p>
        </div>
      </article>

      <article *ngFor="let n of noticias" class="announcement-card">
        <div *ngIf="n.imagen_url" class="card-image">
          <img [src]="environment.apiBase + n.imagen_url" alt="Imagen" />
        </div>
        <div class="card-content">
          <h3>{{n.titulo}}</h3>
          <p class="card-preview">{{n.contenido}}</p>
          <div class="card-meta">
            <span>{{ formatFecha(n.fecha) }}</span>
            <a *ngIf="n.archivo_url" [href]="environment.apiBase + n.archivo_url" target="_blank" class="btn-download">Descargar archivo</a>
          </div>
        </div>
        <div class="card-comments">
          <app-comments [noticiaId]="n._id || n.id"></app-comments>
        </div>
      </article>
    </div>
  </section>
</div>

// src/views/Home.jsx
import React, { useEffect, useState } from "react";
import "./Home.css";
import { toast } from 'react-toastify';
import { motion, AnimatePresence } from 'framer-motion';

const API_URL = "http://localhost:3000";

export default function Home() {
  const [noticias, setNoticias] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchNoticias = async () => {
    try {
      const res = await fetch(`${API_URL}/noticias`);

      if (!res.ok) {
        const txt = await res.text();
        console.error("Error HTTP:", res.status, txt);
        toast.error("Error al cargar noticias (HTTP " + res.status + ")");
        return;
      }

      const data = await res.json();
      setNoticias(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Error de red:", err);
      toast.error("Error de conexión con el servidor");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchNoticias();
  }, []);

  const formatFecha = (f) => {
    if (!f) return "";
    return new Date(f).toLocaleString();
  };

  return (
    <div className="home-container">
      <section className="home-banner">
        <h1>Noticias</h1>
        <p>“Lo nuevo del Tec en un solo lugar: eventos, anuncios y lo más top. ¡No te pierdas nada!”</p>
      </section>

      <section className="announcements-section">
        <h2>Noticias recientes</h2>

        {loading ? (
          <div>Cargando noticias...</div>
        ) : (
          <motion.div
            className="announcements-grid"
            initial="hidden"
            animate="visible"
            exit="hidden"
            variants={containerVariants}
          >
            {noticias.length === 0 ? (
              <article className="announcement-card empty-card">
                <div className="card-content">
                  <h3>Sin noticias por ahora</h3>
                  <p className="card-preview">
                    Aún no se han publicado avisos. Vuelve más tarde para ver
                    las últimas noticias del Instituto Tecnológico de Orizaba.
                  </p>
                </div>
              </article>
            ) : (
              noticias.map((n) => (
                <motion.article key={n.id} className="announcement-card" variants={itemVariants} layout>
                  {n.imagen_url && (
                    <div className="card-image">
                      <img src={API_URL + n.imagen_url} alt="Imagen de la noticia" />
                    </div>
                  )}

                  <div className="card-content">
                    <h3>{n.titulo}</h3>
                    <p className="card-preview">{n.contenido}</p>

                    <div className="card-meta">
                      <span>{formatFecha(n.fecha)}</span>

                      {n.archivo_url && (
                        <a href={API_URL + n.archivo_url} target="_blank" rel="noreferrer" className="btn-download">
                          Descargar archivo
                        </a>
                      )}
                    </div>
                  </div>
                </motion.article>
              ))
            )}
          </motion.div>
        )}
      </section>
    </div>
  );
}

const prefersReduced = typeof window !== 'undefined' && window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const containerVariants = prefersReduced
  ? { hidden: {}, visible: {} }
  : {
      hidden: { opacity: 0 },
      visible: { opacity: 1, transition: { staggerChildren: 0.06 } },
    };

const itemVariants = prefersReduced
  ? { hidden: {}, visible: {} }
  : {
      hidden: { opacity: 0, y: 10 },
      visible: { opacity: 1, y: 0, transition: { duration: 0.25, ease: 'easeOut' } },
    };
