// src/app/views/profile-edit/profile-edit.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { ToastrService } from 'ngx-toastr';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-profile-edit',
  templateUrl: './profile-edit.component.html',
  styleUrls: ['./profile-edit.component.css']
})
export class ProfileEditComponent implements OnInit {
  private _usuario = signal<any | null>(null);
  nombre = '';
  email = '';
  password = '';
  private _guardando = signal(false);

  constructor(private http: HttpClient, public router: Router, private toastr: ToastrService) {}

  ngOnInit(): void {
    try {
      const raw = localStorage.getItem('usuario');
      if (raw) {
        const parsed = JSON.parse(raw);
        this._usuario.set(parsed);
        this.nombre = parsed.nombre;
        this.email = parsed.email;
      }
    } catch {
      this._usuario.set(null);
    }
  }

  async guardar() {
    if (!this._usuario()) {
      this.router.navigate(['/login']);
      return;
    }

    if (!this.nombre || this.nombre.trim() === '') {
      this.toastr.error('✗ El nombre no puede estar vacío', 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      return;
    }

    this._guardando.set(true);
    try {
      const token = localStorage.getItem('token');
      const headers = token ? { Authorization: `Bearer ${token}` } : {};

      const res: any = await firstValueFrom(
        this.http.put(`${environment.apiBase}/auth/profile/${this._usuario().id}`,
          { nombre: this.nombre, password: this.password || undefined },
          { headers: headers as any }
        )
      );

      const localUser = { ...this._usuario(), nombre: this.nombre };
      localStorage.setItem('usuario', JSON.stringify(localUser));
      this._usuario.set(localUser);

      this.toastr.success('✓ Perfil actualizado correctamente', 'Éxito', { positionClass: 'toast-top-right', timeOut: 3000 });
      this.router.navigate(['/dashboard']);
    } catch (err: any) {
      console.error(err);
      const errMsg = err?.error?.error || err?.error?.message || 'Error al actualizar perfil';
      this.toastr.error('✗ ' + errMsg, 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });

      const localUser = { ...this._usuario(), nombre: this.nombre };
      localStorage.setItem('usuario', JSON.stringify(localUser));
      this._usuario.set(localUser);
    } finally {
      this._guardando.set(false);
    }
  }
  get usuario() { return this._usuario(); }
  get guardando() { return this._guardando(); }
}


<div class="profile-edit-container" *ngIf="usuario; else notAuth">
  <div class="profile-card">
    <h2>Editar perfil</h2>
    <form (ngSubmit)="guardar()">
      <div class="form-group">
        <label>Nombre</label>
        <input [(ngModel)]="nombre" name="nombre" [disabled]="guardando" />
      </div>
      <div class="form-group">
        <label>Email</label>
        <input [value]="email" disabled />
        <small>Este correo no se puede modificar.</small>
      </div>
      <div class="form-group">
        <label>Nueva contraseña</label>
        <input type="password" [(ngModel)]="password" name="password" placeholder="Dejar en blanco = sin cambio" [disabled]="guardando" />
      </div>
      <div class="form-actions">
        <button class="btn-save" type="submit" [disabled]="guardando">{{ guardando ? 'Guardando...' : 'Guardar' }}</button>
        <button class="btn-cancel" type="button" (click)="router.navigate(['/dashboard'])" [disabled]="guardando">Cancelar</button>
      </div>
    </form>
  </div>
</div>
<ng-template #notAuth>
  <div class="profile-edit-container">
    <div class="profile-card">
      <h2>No autenticado</h2>
      <p>Inicia sesión para editar tu perfil.</p>
      <div class="form-actions">
        <button class="btn-save" (click)="router.navigate(['/login'])">Ir a iniciar sesión</button>
      </div>
    </div>
  </div>
</ng-template>

// src/views/ProfileEdit.jsx
import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "./ProfileEdit.css"; // si deseas separar los estilos
import { toast } from 'react-toastify';

export default function ProfileEdit() {
  const navigate = useNavigate();

  const [usuario, setUsuario] = useState(null);
  const [nombre, setNombre] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  useEffect(() => {
    try {
      const raw = localStorage.getItem("usuario");
      if (raw) {
        const storedUser = JSON.parse(raw);
        setUsuario(storedUser);
        setNombre(storedUser.nombre);
        setEmail(storedUser.email);
      }
    } catch (e) {
      setUsuario(null);
    }
  }, []);

  const guardar = async (e) => {
    e.preventDefault();
    try {
      const token = localStorage.getItem("token");
      const res = await fetch(`http://localhost:3000/auth/profile/${usuario.id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          ...(token ? { Authorization: `Bearer ${token}` } : {}),
        },
        body: JSON.stringify({ nombre, password: password || undefined }),
      });

      if (!res.ok) {
        if (res.status === 404 || res.status === 501) {
          const localUser = { ...usuario, nombre };
          localStorage.setItem("usuario", JSON.stringify(localUser));
          toast.info("Cambios guardados localmente (API no implementada).", { autoClose: 3500 });
          navigate("/dashboard");
          return;
        }

        const errBody = await res.json().catch(() => ({}));
        toast.error(errBody.error || "Error al actualizar perfil");
        return;
      }

      const updatedUser = await res.json().catch(() => null);
      if (updatedUser) {
        delete updatedUser.password;
        localStorage.setItem("usuario", JSON.stringify(updatedUser));
      } else {
        const localUser = { ...usuario, nombre };
        localStorage.setItem("usuario", JSON.stringify(localUser));
      }

      toast.success("Perfil actualizado!");
      navigate("/dashboard");
    } catch (err) {
      console.error(err);
      const localUser = { ...usuario, nombre };
      localStorage.setItem("usuario", JSON.stringify(localUser));
      toast.info("Cambios guardados localmente (sin conexión).", { autoClose: 3500 });
      navigate("/dashboard");
    }
  };

  if (!usuario) {
    return (
      <div className="profile-edit-container">
        <div className="profile-card">
          <h2>No autenticado</h2>
          <p>Inicia sesión para editar tu perfil.</p>
          <div className="form-actions">
            <button className="btn-save" onClick={() => navigate("/login")}>
              Ir a iniciar sesión
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="profile-edit-container">
      <div className="profile-card">
        <h2>Editar perfil</h2>

        <form className="profile-form" onSubmit={guardar}>
          <div className="form-group">
            <label>Nombre</label>
            <input
              value={nombre}
              onChange={(e) => setNombre(e.target.value)}
            />
          </div>

          <div className="form-group">
            <label>Email</label>
            <input value={email} disabled />
            <small>Este correo no se puede modificar.</small>
          </div>

          <div className="form-section">
            <h3>Cambiar contraseña</h3>
            <div className="form-group">
              <label>Nueva contraseña</label>
              <input
                type="password"
                placeholder="Dejar en blanco = sin cambio"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
              <small>
                Si dejas este campo vacío, tu contraseña seguirá igual.
              </small>
            </div>
          </div>

          <div className="form-actions">
            <button type="submit" className="btn-save">
              Guardar
            </button>
            <button
              type="button"
              className="btn-cancel"
              onClick={() => navigate("/dashboard")}
            >
              Cancelar
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
