// src/app/views/register/register.component.ts
import { Component } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';
import { environment } from '../../../environments/environment';
import { ToastrService } from 'ngx-toastr';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  nombre = '';
  email = '';
  password = '';

  constructor(private http: HttpClient, private router: Router, private toastr: ToastrService) {}

  async handleRegister() {
    if (!this.nombre || !this.email || !this.password) {
      this.toastr.error('Por favor completa todos los campos');
      return;
    }
    try {
      const res: any = await firstValueFrom(
        this.http.post(`${environment.apiBase}/auth/register`, { nombre: this.nombre, email: this.email, password: this.password, rol: 'usuario' })
      );
      this.toastr.success('Registro exitoso. Por favor inicia sesión.');
      this.router.navigate(['/login']);
    } catch (err: any) {
      const errMsg = err?.error?.error || err?.error?.message || 'Error al registrarse';
      this.toastr.error(errMsg);
      console.error('Register error:', err);
    }
  }
}

<div class="register-container">
  <div class="register-card">
    <h2>Registro</h2>
    <form (ngSubmit)="handleRegister()">
      <div class="form-group">
        <label>Nombre</label>
        <input [(ngModel)]="nombre" name="nombre" required />
      </div>
      <div class="form-group">
        <label>Email</label>
        <input type="email" [(ngModel)]="email" name="email" required />
      </div>
      <div class="form-group">
        <label>Contraseña</label>
        <input type="password" [(ngModel)]="password" name="password" required />
      </div>
      <button class="btn-submit" type="submit">Registrarse</button>
    </form>
  </div>
</div>

// src/views/Register.jsx
import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./Register.css"; // Opcional si tienes estilos separados
import { toast } from 'react-toastify';

export default function Register() {
  const navigate = useNavigate();

  const [nombre, setNombre] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const handleRegister = async (e) => {
    e.preventDefault();

    try {
      const res = await fetch("http://localhost:3000/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          nombre,
          email,
          password,
          rol: "usuario",
        }),
      });

      const data = await res.json();
      if (!res.ok) return toast.error(data.error || "Error al registrar");

      toast.success("Registro exitoso! Ahora puedes iniciar sesión");
      navigate("/login");

    } catch (err) {
      console.error(err);
      toast.error("Error de conexión con el servidor");
    }
  };

  return (
    <div className="register-container">
      <div className="register-card">
        <h2>Registro</h2>

        <p className="register-subtitle">
          Crea tu cuenta para recibir las noticias del Instituto Tecnológico de Orizaba.
        </p>

        <form onSubmit={handleRegister} className="register-form">
          <div className="form-group">
            <label htmlFor="nombre">Nombre</label>
            <div className="input-wrapper">
              <span className="input-icon">👤</span>
              <input
                id="nombre"
                type="text"
                placeholder="Tu nombre completo"
                required
                value={nombre}
                onChange={(e) => setNombre(e.target.value)}
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="email">Email</label>
            <div className="input-wrapper">
              <span className="input-icon">✉️</span>
              <input
                id="email"
                type="email"
                placeholder="ejemplo@gmail.com"
                required
                value={email}
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="password">Contraseña</label>
            <div className="input-wrapper">
              <span className="input-icon">🔒</span>
              <input
                id="password"
                type="password"
                placeholder="Mínimo 6 caracteres"
                required
                value={password}
                onChange={(e) => setPassword(e.target.value)}
              />
            </div>
            <small className="hint">
              Usa una contraseña segura que recuerdes con facilidad.
            </small>
          </div>

          <button type="submit" className="btn-submit">
            Registrarse
          </button>
        </form>

        <p className="login-link">
          ¿Ya tienes cuenta? <Link to="/login">Inicia sesión</Link>
        </p>
      </div>
    </div>
  );
}
