// src/views/Dashboard.jsx
import React, { useEffect, useState } from "react";
import "./Dashboard.css"; // Opcional si usarás estilos
import { toast } from 'react-toastify';

const API_URL = "http://localhost:3000";

export default function Dashboard() {
  const [usuario, setUsuario] = useState(null);
  const [noticias, setNoticias] = useState([]);
  const [cargando, setCargando] = useState(true);

  useEffect(() => {
    const rawUser = localStorage.getItem("usuario");
    if (rawUser) {
      try {
        setUsuario(JSON.parse(rawUser));
      } catch {
        setUsuario(null);
      }
    }

    fetch(`${API_URL}/noticias`)
      .then((res) => res.json())
      .then((data) => {
        setNoticias(Array.isArray(data) ? data : []);
      })
      .catch((err) => {
        console.error(err);
        toast.error("Error al conectarse al servidor");
      })
      .finally(() => setCargando(false));
  }, []);

  return (
    <div className="dashboard-container">
      <h2>Noticias publicadas</h2>

      {cargando ? (
        <div>Cargando noticias...</div>
      ) : noticias.length === 0 ? (
        <div>No hay noticias registradas.</div>
      ) : (
        <ul>
          {noticias.map((n) => (
            <li key={n.id} className="announcement-card">
              <div className="card-content">
                <h3>{n.titulo}</h3>
                <p className="card-preview">{n.contenido}</p>

                <div className="file-info">
                  {n.imagen_url && (
                    <img
                      src={API_URL + n.imagen_url}
                      alt="Imagen de la noticia"
                      className="news-image"
                    />
                  )}
                  {n.archivo_url && (
                    <a
                      href={API_URL + n.archivo_url}
                      target="_blank"
                      rel="noreferrer"
                      className="btn-download"
                    >
                      Descargar archivo
                    </a>
                  )}
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

// src/app/views/dashboard/dashboard.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../../environments/environment';
import { ToastrService } from 'ngx-toastr';
import { toSignal } from '@angular/core/rxjs-interop';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  private _usuario = signal<any | null>(null);
  private _noticias = signal<any[]>([]);
  private _cargando = signal(true);
  environment = environment;
  constructor(private http: HttpClient, private toastr: ToastrService) {}
  ngOnInit(): void {
    this.cargarDatos();
  }
  cargarDatos() {
    try {
      const rawUser = localStorage.getItem('usuario');
      if (rawUser) {
        this._usuario.set(JSON.parse(rawUser));
      }
    } catch (e) {
      this._usuario.set(null);
    }
    // carga noticias desde API
    this._cargando.set(true);
    try {
      this.http.get(`${environment.apiBase}/noticias`).subscribe({
        next: (res: any) => {
          this._noticias.set(Array.isArray(res) ? res : []);
        },
        error: (err) => {
          console.error(err);
          this.toastr.error('✗ Error al cargar noticias', 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
          this._noticias.set([]);
        },
        complete: () => {
          this._cargando.set(false);
        }
      });
    } catch (err) {
      console.error(err);
      this.toastr.error('✗ Error al cargar noticias', 'Error', { positionClass: 'toast-top-right', timeOut: 3000 });
      this._noticias.set([]);
      this._cargando.set(false);
    }
  }

  formatFecha(f: any) {
    try {
      return new Date(f).toLocaleString();
    } catch {
      return f;
    }
  }
  get usuario() { return this._usuario(); }
  get noticias() { return this._noticias(); }
  get cargando() { return this._cargando(); }
}

<div class="dashboard-container">
  <section class="dashboard-header">
    <h1>Mi Panel de Control</h1>
    <div *ngIf="usuario" class="user-info">
      <p><strong>Bienvenido, {{ usuario.nombre }}</strong></p>
      <p class="user-email">{{ usuario.email }}</p>
    </div>
  </section>

  <section class="news-section">
    <h2>Noticias publicadas</h2>

    <div *ngIf="cargando" class="loading">
      <p>Cargando noticias...</p>
    </div>

    <div *ngIf="!cargando && noticias.length === 0" class="empty-state">
      <p>No hay noticias registradas aún.</p>
    </div>

    <ul *ngIf="!cargando && noticias.length > 0" class="news-list">
      <li *ngFor="let n of noticias" class="announcement-card">
        <div class="card-content">
          <h3>{{ n.titulo }}</h3>
          <p class="card-preview">{{ n.contenido }}</p>

          <div *ngIf="n.imagen_url || n.archivo_url" class="file-info">
            <img *ngIf="n.imagen_url" [src]="environment.apiBase + n.imagen_url" alt="Imagen de la noticia" class="news-image" />
            <a *ngIf="n.archivo_url" [href]="environment.apiBase + n.archivo_url" target="_blank" rel="noreferrer" class="btn-download">
              Descargar archivo
            </a>
          </div>

          <div class="card-meta">
            <span class="date">{{ formatFecha(n.fecha) }}</span>
          </div>
        </div>
      </li>
    </ul>
  </section>
</div>
